apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-api-gateway
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: kistora/ms-api-gateway:latest
          imagePullPolicy: Always
          name: api-gateway
          ports:
            - containerPort: 8080
          env:
            - name: URL_MS_AUTH
              value: "ms-auth-lb"
            - name: URL_MS_COMMENT
              value: "ms-comment-lb"
            - name: URL_MS_POST
              value: "ms-post-lb"
            - name: URL_MS_USER
              value: "ms-user-lb"
