apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-post
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ms-post
    spec:
      containers:
        - image: kistora/ms-post:latest
          imagePullPolicy: Always
          name: ms-post
          ports:
            - containerPort: 8080
